disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - line_length
  - trailing_whitespace
  - type_body_length
  - type_name
  - vertical_whitespace
  - void_return

excluded:
  - Pods
  - Carthage

function_parameter_count:
  warning: 6
  error: 8

variable_name:
  excluded:
    - i
    - id
    - ok
    - to
    - up
    - vc
    - x
    - y
