osx_image: xcode9
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - carthage update --platform ios
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/iExtra.xcworkspace -scheme iExtra-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
