osx_image: xcode10
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - carthage update --platform ios

script:
  - set -o pipefail && xcodebuild -project "iExtra.xcodeproj" -scheme "iExtra" -sdk "iphonesimulator" | xcpretty -c
  - pod lib lint
  - fastlane test